# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-28 02:32
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.IntegerField(choices=[(3, b'default'), (0, b'local messages'), (1, b'email'), (4, b'email for every new thread (mailing list mode)')], db_index=True, default=0)),
                ('unread', models.BooleanField(default=True)),
                ('sent_at', models.DateTimeField(db_index=True, null=True)),
            ],
            options={
                'db_table': 'messages_message',
            },
        ),
        migrations.CreateModel(
            name='MessageBody',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(verbose_name='Text')),
                ('subject', models.CharField(max_length=120, verbose_name='Subject')),
                ('sent_at', models.DateTimeField(verbose_name='sent at')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sent_messages', to=settings.AUTH_USER_MODEL, verbose_name='Sender')),
                ('parent_msg', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='next_messages', to='messages.MessageBody', verbose_name='Parent message')),
            ],
            options={
                'db_table': 'messages_messagebody',
            },
        ),
        migrations.AddField(
            model_name='message',
            name='body',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='messages.MessageBody', verbose_name='Message'),
        ),
        migrations.AddField(
            model_name='message',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recipients', to=settings.AUTH_USER_MODEL, verbose_name='Recipient'),
        ),
    ]
