# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-28 00:42
from __future__ import unicode_literals

import biostar.apps.users.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('sites', '0002_alter_domain_unique'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('email', models.EmailField(db_index=True, max_length=255, unique=True, verbose_name='Email')),
                ('name', models.CharField(default='', max_length=255, verbose_name='Name')),
                ('is_active', models.BooleanField(default=True)),
                ('is_admin', models.BooleanField(default=False)),
                ('is_staff', models.BooleanField(default=False)),
                ('type', models.IntegerField(choices=[(0, 'User'), (1, 'Moderator'), (2, 'Admin'), (3, 'Blog')], default=0)),
                ('status', models.IntegerField(choices=[(0, 'New User'), (1, 'Trusted'), (2, 'Suspended'), (3, 'Banned')], default=0)),
                ('new_messages', models.IntegerField(default=0)),
                ('badges', models.IntegerField(default=0)),
                ('score', models.IntegerField(default=0)),
                ('activity', models.IntegerField(default=0)),
                ('flair', models.CharField(default='', max_length=15, verbose_name='Flair')),
                ('site', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='sites.Site')),
            ],
            options={
                'abstract': False,
            },
            managers=[
                ('objects', biostar.apps.users.models.LocalManager()),
            ],
        ),
        migrations.CreateModel(
            name='EmailList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_created=True)),
                ('email', models.EmailField(db_index=True, max_length=255, unique=True, verbose_name='Email')),
                ('type', models.IntegerField(default=0)),
                ('active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.CharField(db_index=True, max_length=255, unique=True)),
                ('last_login', models.DateTimeField()),
                ('date_joined', models.DateTimeField()),
                ('location', models.CharField(blank=True, default='', max_length=255)),
                ('website', models.URLField(blank=True, default='', max_length=255)),
                ('scholar', models.CharField(blank=True, default='', max_length=255)),
                ('twitter_id', models.CharField(blank=True, default='', max_length=255)),
                ('my_tags', models.TextField(blank=True, default='', max_length=255)),
                ('info', models.TextField(blank=True, default='', null=True)),
                ('message_prefs', models.IntegerField(choices=[(3, b'default'), (0, b'local messages'), (1, b'email'), (4, b'email for every new thread (mailing list mode)')], default=0)),
                ('flag', models.IntegerField(default=0)),
                ('watched_tags', models.CharField(blank=True, default='', max_length=100)),
                ('digest_prefs', models.IntegerField(choices=[(0, 'Never'), (1, 'Daily'), (2, 'Weekly'), (3, 'Monthly')], default=2)),
                ('opt_in', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(db_index=True, max_length=50)),
            ],
        ),
        migrations.AddField(
            model_name='profile',
            name='tags',
            field=models.ManyToManyField(blank=True, to='users.Tag'),
        ),
        migrations.AddField(
            model_name='profile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
